// <auto-generated />
using MicroServices.Samples.Services.Basket.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Basket.API.Migrations
{
    [DbContext(typeof(BasketDbConText))]
    [Migration("20220715034348_Initital")]
    partial class Initital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MicroServices.Samples.Services.Basket.API.Application.Models.BasketItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("BasketItemId");

                    b.Property<string>("CustomerBasketId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ProductName");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quantity");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("Tbl_BasketItem_Pk");

                    b.HasIndex("CustomerBasketId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Tbl_BasketItem", (string)null);
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Basket.API.Application.Models.CustomerBasket", b =>
                {
                    b.Property<string>("CusTomerId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerId");

                    b.HasKey("CusTomerId")
                        .HasName("Tbl_CustomerBasket_Id");

                    b.ToTable("Tbl_CustomerBasket", (string)null);
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Basket.API.Application.Models.BasketItem", b =>
                {
                    b.HasOne("MicroServices.Samples.Services.Basket.API.Application.Models.CustomerBasket", null)
                        .WithMany("Items")
                        .HasForeignKey("CustomerBasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Basket.API.Application.Models.CustomerBasket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
