// <auto-generated />
using System;
using MicroServices.Samples.Services.Ordering.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Ordering.API.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20220715041444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerId");

                    b.Property<string>("IdentityId")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IdentityId");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CustomerName");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CustomerPhoneNumber");

                    b.HasKey("Id")
                        .HasName("Tbl_CustomerId_PK");

                    b.ToTable("Tbl_Customer", (string)null);
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("OrderId");

                    b.Property<string>("AdditionalAddress")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AdditionalAddress");

                    b.Property<string>("City")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("City");

                    b.Property<string>("CustomerId")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CustomerId");

                    b.Property<string>("District")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("District");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("OrderDate");

                    b.Property<string>("Street")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Street");

                    b.HasKey("Id")
                        .HasName("Tbl_OrderId_PK");

                    b.HasIndex("CustomerId");

                    b.ToTable("Tbl_Order", (string)null);
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("OrderItemId");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OrderId1")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ProductName");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId1");

                    b.ToTable("Tbl_OrderItem", (string)null);
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.Order", b =>
                {
                    b.HasOne("MicroServices.Samples.Services.Ordering.API.Application.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.OrderItem", b =>
                {
                    b.HasOne("MicroServices.Samples.Services.Ordering.API.Application.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId1");
                });

            modelBuilder.Entity("MicroServices.Samples.Services.Ordering.API.Application.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
